# 1. Server configuration
spring.application.name=API-GATEWAY
server.port=8080

# 2. Route 1: Auth Service Configuration
spring.cloud.gateway.server.webflux.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:7071
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# 3. Route 2: Employee Profile Service Configuration
spring.cloud.gateway.server.webflux.routes[1].id=EMPLOYEE-PROFILE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:7072
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/employee/**

# This tells the gateway to run our custom GatewayAuthenticationFilter before routing
spring.cloud.gateway.server.webflux.routes[1].filters[0]=GatewayAuthenticationFilter

# 4. Route 3: Admin Service Configuration
spring.cloud.gateway.server.webflux.routes[2].id=ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:7073
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=GatewayAuthenticationFilter

# 5. Route 4: Attendance Service Configuration
spring.cloud.gateway.server.webflux.routes[3].id=ATTENDANCE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:7074
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/attendance/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=GatewayAuthenticationFilter

# 6. Route 5:Notification Service Configuration
spring.cloud.gateway.server.webflux.routes[4].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=ws://localhost:7075
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/ws/**
#spring.cloud.gateway.server.webflux.routes[4].filters[0]=GatewayAuthenticationFilter

# 7. Route 6:Leave Service Configuration
spring.cloud.gateway.server.webflux.routes[5].id=LEAVE-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:7076
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/leave/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=GatewayAuthenticationFilter

jwt.secret=9d583de3633b4c475e7e50b67d3bc39749fde10398df52e2ccf299a415f85840

jwt.expirationMs=1800000
