# 1. Server configuration
spring.application.name=EMPLOYEE-GATEWAY
server.port=8080

# ===========================
# Eureka Client Configuration
# ===========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

# 2. Route 1: Auth Service Configuration
spring.cloud.gateway.server.webflux.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=GatewayAuthenticationFilter

# 3. Route 2: Employee Profile Service Configuration
spring.cloud.gateway.server.webflux.routes[1].id=EMPLOYEE-PROFILE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://EMPLOYEE-PROFILE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/employee/**

# This tells the gateway to run our custom GatewayAuthenticationFilter before routing
spring.cloud.gateway.server.webflux.routes[1].filters[0]=GatewayAuthenticationFilter

# 4. Route 3: Admin Service Configuration
spring.cloud.gateway.server.webflux.routes[2].id=ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=GatewayAuthenticationFilter
spring.cloud.gateway.server.webflux.routes[2].filters[1]=StripPrefix=2

# 5. Route 4: Attendance Service Configuration
spring.cloud.gateway.server.webflux.routes[3].id=ATTENDANCE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ATTENDANCE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/attendance/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=GatewayAuthenticationFilter

# 6. Route 5:Notification Service Configuration
spring.cloud.gateway.server.webflux.routes[4].id=NOTIFICATION-SERVICE
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/ws/**

# 7. Route 6:Leave Service Configuration
spring.cloud.gateway.server.webflux.routes[5].id=LEAVE-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=lb://LEAVE-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/leave/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=GatewayAuthenticationFilter

jwt.secret=9d583de3633b4c475e7e50b67d3bc39749fde10398df52e2ccf299a415f85840

jwt.expirationMs=1800000

# ===========================
# Swagger UI Configuration
# ===========================

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# 1. Auth Service
springdoc.swagger-ui.urls[0].name=AUTH-SERVICE
springdoc.swagger-ui.urls[0].url=/api/auth/v3/api-docs

# 2. Employee Profile Service
springdoc.swagger-ui.urls[1].name=EMPLOYEE-PROFILE-SERVICE
springdoc.swagger-ui.urls[1].url=/api/employee/v3/api-docs

# 3. Admin Service
springdoc.swagger-ui.urls[2].name=ADMIN-SERVICE
springdoc.swagger-ui.urls[2].url=/api/admin/v3/api-docs

# 4. Attendance Service
springdoc.swagger-ui.urls[3].name=ATTENDANCE-SERVICE
springdoc.swagger-ui.urls[3].url=/api/attendance/v3/api-docs

# 5. Notification Service
springdoc.swagger-ui.urls[4].name=NOTIFICATION-SERVICE
springdoc.swagger-ui.urls[4].url=/api/notification/v3/api-docs

# 6. Leave Service
springdoc.swagger-ui.urls[5].name=LEAVE-SERVICE
springdoc.swagger-ui.urls[5].url=/api/leave/v3/api-docs