# 1. Server configuration
spring.application.name=API-GATEWAY

# 2. Route 1: Auth Service Configuration
spring.cloud.gateway.server.webflux.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# 3. Route 2: Employee Profile Service Configuration
spring.cloud.gateway.server.webflux.routes[1].id=EMPLOYEE-PROFILE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/employee/**

# This tells the gateway to run our custom GatewayAuthenticationFilter before routing
spring.cloud.gateway.server.webflux.routes[1].filters[0]=GatewayAuthenticationFilter

# 4. Route 3: Admin Service Configuration
spring.cloud.gateway.server.webflux.routes[2].id=ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=GatewayAuthenticationFilter
jwt.secret=9d583de3633b4c475e7e50b67d3bc39749fde10398df52e2ccf299a415f85840

jwt.expirationMs=1800000
