# ====================
# Server Configuration
# ====================
spring.application.name=AUTH-SERVICE
#server.port=7071
server.port=0
server.address=0.0.0.0

# =================================
# PostgreSQL database configuration
# =================================
spring.datasource.url=jdbc:postgresql://localhost:5432/developmentauthservicedb
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================
# Hibernate settings
# ===================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9d583de3633b4c475e7e50b67d3bc39749fde10398df52e2ccf299a415f85840

jwt.expirationMs=1800000

# ===========================
# Eureka Client Configuration
# ===========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===================================================================
# Spring Mail Configuration
# ===================================================================

# SMTP Server Details (Using Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Credentials (Do not hardcode production passwords here!)
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Protocols and Security Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Connection Timeouts (Prevents your app from hanging if the mail server is down)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000