#spring.application.name=NotificationService
spring.profiles.active=prod
#spring.profiles.active=dev

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/api/notifications/internal/v3/api-docs