spring.profiles.active=prod
#spring.profiles.active=dev

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/api/leave/v3/api-docs

#  swagger url
gateway.server.urls=http://localhost:8080,https://stage4.optipacetech.com:9111
gateway.server.descriptions=local,testing